config:
  spec:
    destination:
      server: https://kubernetes.default.svc
    source:
      repoURL: https://github.com/son-lam-rakkardigital/argocd-example-apps
      targetRevision: master

applications:
  - name: guestbook
    namespace: 'default'
    project: 'demo'

  - name: helm-guestbook
    namespace: 'default'
    project: 'demo'
    tool:
      helm:
        releaseName: helm-guestbook

